apiVersion: v1
kind: Secret
metadata:
    name: pantheon-pg-backup-s3
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:ep3HMO0odh3WpY4w4lzk7eS5lKM=,iv:vEzBQSkMd7PQVyVmkAuGiX8FOAml4ap+aT0yTAi9xxw=,tag:GOaKhrmPq7XPBNQ2ArBxGA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:a8V7Ee2EVnmwY2iTU4CeZX78c/9sQcvOpaSlv2BM7hvx7JmQem/aBw==,iv:GT8p6cn86sLlOLjAW65zyOaJZRLKXj6Z12m0GEz5uHc=,tag:9nNLEe4AqgZP1q+mSdDK8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVmRQVDRaOTNlMWx6YjAx
            VUhSaHM0Wk1CN3ZYR21JSlo3dVZGZVlqalZBClFSK2JKWmhnVlhqQkhEUStJWlVG
            U1ZEN3VhVHZzekYzR1E2c01Wend2L0kKLS0tIDJjdGliUkpvM21abHhySDBsOGw5
            RzVQU0U0S1hkYTJvcTNhS2s1MVFlNUEKP5ceFIDTxDX3liE6pk3mq/O31JBqeS26
            lFSKsvxPPkqxiHzt/DomKYQAzX7fQIE+NOqhONetE+npphxhsDhJUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mcj4tr2sfgvc3h2ekqjsvm4s4gh0rs74nqnn0yapfzdtlgkqxysqj6wdrl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T19:44:14Z"
    mac: ENC[AES256_GCM,data:ywlSUhFQ+Sn2yIkJ7/gtbJlAFAc5ZvBSVQPErBsQijh0TIj+lJVf1x21dMd9dwqfnRfOg3JlexO/ZDZMylLRnXQR0ceC78NUsN4NuxFqTo/CvPso1EmUOfpB6G4WcnItuXNcX40qBCioYSCxn1aM7RPdUO/Qh6fjilUFrOAsmgI=,iv:XgIfY6BytwsKyIPW9RoeksrhJsm9j+TrRCutNWEKvOc=,tag:YVhTA+a27Y9D+PDr6O/Tsw==,type:str]
    version: 3.13.1
