apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pantheon-pg
  namespace: databases
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql
    major: 18
  instances: 2
  enableSuperuserAccess: true
  superuserSecret:
    name: pantheon-pg-superuser
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
  bootstrap:
    initdb:
      database: app
      owner: app
  storage:
    size: 10Gi
    storageClass: qnap-iscsi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
