apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - namespace.yaml
  - secret.yaml
  - backup-secret.yaml
  - imagecatalog.yaml
  - cluster.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - paperless-db-role-secret.yaml
  - paperless-role.yaml
  - paperless-database.yaml
