apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-role
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:r4J1zkF6Z7TI,iv:IVTjISXywQySF39UAuBfUdIVEkfAD+i3kJJKflEnjeE=,tag:P8VCkvYij2mM0VfSx7Zlig==,type:str]
    password: ENC[AES256_GCM,data:Y+Z9QwaJqmRx3AFJSkX7RgiBmPNEwQfIsG3GzM+kpkE=,iv:l45ZfwXSQuI0xPvgvtAC1AGX14AeLiiknah4BnlCf6I=,tag:jAF7kXg2sfzqJQxlPLO6MQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdXJaSVJ5ZytDR1JrMVRk
            UG1hb01TZy9XZXBZTHhRSWtqaW94YXZkTVRBCmlFK0RmYlNwN2N1T3RwS2psUzZ0
            UlI5a1VacitKR0tHcEk1VTZNd01ubGMKLS0tIHpJZVg5K0oyV3piNGY5NjhWbEU1
            OWltSUJFZndLVlVrVG8zWlYxUU1URkEKmCd4Q0q8A5ribXyyI6dC+yywZXGSCm9L
            o6YBVt1Y90O72heYxNCaJBJpOh2/Ae6Xth4ljEZ82ws1YWK23PqNbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mcj4tr2sfgvc3h2ekqjsvm4s4gh0rs74nqnn0yapfzdtlgkqxysqj6wdrl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T13:37:16Z"
    mac: ENC[AES256_GCM,data:+2U1BDyIMZk+F+NZNLuTMrS9Ikyxqc22JWF44fwsjc8n5RXgKdKW1ijPdX+1cPIKAuJ09hcX+ZyVfCKkM0K4y9lmgoETxx4x5hkZFZXoepUXxV5/yv1pM0AHyNZFK8Ae7sSCJIZNC6JUz3TtIHdSIN8LAYKbL47yJyQyOZ0ZD1s=,iv:rZ9R7TWSc3ejCIIHlZ9FFD03714SYogQeZqgdorWxvE=,tag:OMhBbX6A5y80GxvRUcRdJw==,type:str]
    version: 3.13.2
