apiVersion: v1
kind: Secret
metadata:
    name: paperless-test-db-role
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:GN0+vMVLg1Kfs1F23oE=,iv:Sy5qg8yWBA0CCVZH7Mhpj0jHezuacM6GVLfF+1AeZ2I=,tag:TaIpUeXqTrcIW+0fR4uJNQ==,type:str]
    password: ENC[AES256_GCM,data:DNeTkmxc+OVpGyaUcltpvRI=,iv:pYSk78Nc9T7oioN6yQOSyjqsa4jPCRbPC5BzIfcVUBY=,tag:5bD2dESTtBfKeIhpOec79g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0am15c083S2hTOUxvZG9Q
            Wlh6MjJ1Wjlhb1NhOTljRGJ6M0ZJMGg4ZzA0CkJZUzlIUmRBQUl3ZURDMHhGOHNY
            aFBxZ3J2RXU4T0Q5a3l5dkd0TEFLaUUKLS0tIG1Nb3FkOHNqN2RpWTZzMGJjMHBu
            OW94RVlNZ1NWMmNDOVphaGpBSVhtT2MKMOJ70rvKC0Y170nTgTcW04XpoONt4JbQ
            OlRz04ESf09ZfQgHlwW4e5y1K5ETldloU3yJJeGQCrmEvoFW7w+ulA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mcj4tr2sfgvc3h2ekqjsvm4s4gh0rs74nqnn0yapfzdtlgkqxysqj6wdrl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T13:09:20Z"
    mac: ENC[AES256_GCM,data:yQVGEqlaCq/QH4laBkhbvagEgwt1y7MpZ8IcRa0+kSK3WrYKlWDFE6augE4pLJLTG3pVQ25kcbEEf+SSsOWH/m4Mf4EeaF3n6PmaG5fzsaqHo+rs8P66zZaK41O3gPZJR7aSWPWkgnKG5CkR36+CgIHYiDjkEmjWOolKQF6OZPU=,iv:03hwG9iJgT4TrHwwPiEenm9GZZg/5qS1vZFKBY0Sehk=,tag:WJ05hQMhfxSy66ij4SPA2Q==,type:str]
    version: 3.13.3
