apiVersion: v1
kind: Secret
metadata:
    name: pantheon-pg-superuser
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:uk2tRXTpRZA=,iv:m7QhOQpfQCaR8CfiGYJPOBul+QWFW2+oMobVvhSAfRg=,tag:Jlq/p57D8gdGzmk5fBbNMw==,type:str]
    password: ENC[AES256_GCM,data:9bKAxzf0dsweOl74toys,iv:ugVEyqo9FCbzIXMUYLnPKmt0l+o3cvWNJeCBbOWbE8I=,tag:9tvfG+1LITE+9pES9WKjiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRDNMYWlLT3NJRTA4QzV0
            QmhMTERnZ2JYUy9YNHhMdCtST0xkd2JONjBBCjd0Z2l1NjVmaGRxelMwUjB4a3NJ
            U05DSm1FeTBLV0N6ZHF3U1Y4NnhHZTgKLS0tIGx6Q3Q2S0JoR3d0VVpxdEdLNDZX
            R1NZcUdKeEJhbDd6aVgwSHRYMFMwMGsKNKPpBNQXlnGElBc05TYF0TMMzPbG5PbO
            QX6XOtjOpPHH5SpAWus0sKHUazV9IWNwBm6i0IxaAQ3yhJY/tZUvcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mcj4tr2sfgvc3h2ekqjsvm4s4gh0rs74nqnn0yapfzdtlgkqxysqj6wdrl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T15:22:57Z"
    mac: ENC[AES256_GCM,data:SYkXMEslNdHLvZPHtQkzV1dhNIYY2/YJFQDBAVklAaNcEKwnRMl5BH5m6GmF7EnkFGbXnToloyJEA9yWbEChK9GKk1aqtZFmPcJpmwvBtBg4bOB6xVQVQTW5AG7vozehrlXpek39a7KC+uJC3482+ZQjV6xv9r6Z64gyjuWQXSY=,iv:nXWGeFHQdBrUiVCnel5fjmiS1CkuN6HjG6KOjwoSD8g=,tag:B7xZFQWiujY2SM6AffSDzA==,type:str]
    version: 3.13.1
