apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:aqwnqkrkcOB2R3sjX7jkFBDzYHA+Mg0s0HfXlh6nDJ9HvZJuv15tNZ6h00TiSv7YgWNdOQ35C09cd3SlVQTlzn339K+O5NdeWQ/tQ0awD8pYz9+BEaMBTyjJYDq165FAmdfGBpB6pRKvlBE4EE116JIKIPYNB6KuKxm/pSFCw2+JsuC1udFY3FfwdE8ciLn+jwa0bq67fT5s9Pq4ApEqyrzJRsLcpZRzUbPRm07iyAiYsLlOQ6OomekLcD9qpFdbDyoxMMO/ytzPDCZoUQyJWDsu5YIGL3FtMBey5f3B5w27JvI8MsqCeNskx/c=,iv:PFAGv3NK05Pu8uLdGK1oDcfluBXjoVG6mvHAlb/Gqfw=,tag:57e/g7JLMApgY2mFRf5djw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1c8x9n79ak4ss8wv45aexsf8r7w8w6mt6hvneu58hqrazdd2syc8q968jyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZHl0eU1aRS9GR3hlemp3
            UWIxTzhMbk1zYVB6Q056eDN5T29OR2l2WGdVCmQvaDhSLzFNTi9SazhzMzBIQ08y
            ekoxSWk4YUlJV29yTDFPeTJRQVBxdkkKLS0tIDRyUG5ZNVlXTTlRSXBsOGEzUVhs
            Y0dIWTVwbmQyV1ZZZnVHZDdPOHBUOHMK1gIwl31Trr67Qg3/d4ahdJZCeN1hqJNn
            xBAWo2538yJTfyNaKRhC0ZYi+a6nW/hnIPWG1cPg5pjr408KF6zn/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-24T20:04:34Z"
    mac: ENC[AES256_GCM,data:OLB2xQtnEXFOLY+mq5kjF7aFgtPhYNwTX9+9UDUWeiwmDzeMg50P5Dgh019vtMeNZyYGy2GQBaaFjfq+DAGtSuo+8Ezlo6K+X3JaYlt0KS1IgQRg4hHY3VqyfRmSSxGHJq8funlr5Ixc7TLkun5Jw0F6Ifb5WY7SoZzE7qYpSuc=,iv:7tjEaos3p+RXKFVns/qMUhi2JycX95G9+5L34jF7BLc=,tag:3ptP51pcZ3DoVKXgxmuvfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
