apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true
    ingress: false
  settings.yaml: |
    title: Pantheon
    headerStyle: clean
    background:
      image: https://images.unsplash.com/photo-1644088379091-d574269d422f?q=80&w=2186&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
      blur: sm
      saturate: 50
      brightness: 50
      opacity: 40
    quicklaunch:
      provider: custom
      url: https://www.ecosia.org/search?q=
      target: _blank
      suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
    layout:
      Services:
        style: row
        columns: 3
      Infrastruktur:
        style: row
        columns: 4
      Netzwerk:
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  docker.yaml: ""
  proxmox.yaml: ""
  services.yaml: |
    - Services:
        - Paperless-ngx:
            icon: paperless-ngx.png
            href: http://192.168.178.42:8010/
            description: Dokumentenmanagement (noch auf QNAP)
    - Infrastruktur:
        - QNAP NAS:
            icon: qnap.png
            href: http://192.168.178.42:8080/
            description: TS-453B Nostromo
        - Proxmox VE:
            icon: proxmox.png
            href: https://192.168.178.160:8006/
            description: VM-Host
        - Sidero Omni:
            icon: talos.png
            href: https://omni.rm-it.org/
            description: Cluster-Management
    - Netzwerk:
        - FRITZ!Box:
            icon: fritzbox.png
            href: http://192.168.178.1/
            description: Internet-Gateway
        - AdGuard Home:
            icon: adguard-home.png
            href: http://192.168.178.53/
            description: DNS-Filter
        - MikroTik Switching:
            icon: mikrotik.png
            href: http://192.168.178.144/
            description: RouterOS
        - MikroTik Kubernetes:
            icon: mikrotik.png
            href: http://192.168.178.171/
            description: RouterOS
        - Netgear Switch:
            icon: netgear.png
            href: http://192.168.178.45/
            description: Managed Switch
  bookmarks.yaml: |
    - Entwicklung:
        - GitHub:
            - abbr: GH
              href: https://github.com/RicoMueller/k8s-cluster
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Pantheon"
        nodes:
          show: false
    - search:
        provider: custom
        url: https://www.ecosia.org/search?q=
        suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
        target: _blank
