apiVersion: v1
kind: Secret
metadata:
    name: homepage-widgets
    namespace: homepage
stringData:
    HOMEPAGE_VAR_PROXMOX_TOKEN_ID: ENC[AES256_GCM,data:IrVsbOAXkr/X9gMnychoooggLKF8,iv:5Aw0e5qnWDGUm3Do1FWLBIYbu797+CajLagnzJPbis0=,tag:ytzDMx701ZGxeUnyTlXoAQ==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:Jun9ArE/VHQAj5pEtADVB+VKjVuKFTXcc4ewHkjenPpTe7Y9,iv:msU6VBoUspZK/pmFx17dTf18o5DnIZz8C6Mkx5RCv2E=,tag:kNh9IeZ1Sc88UjE/yKJk3A==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:K8JIrA==,iv:Jw4K1YvitXVv5A65UYDAAbH3E5fU+4HNBOvF4dc7yTE=,tag:5nmZEwYMIahPhMxCSh+4lw==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:3GIc1RO807SfSXh/9A22,iv:kYoJED3BRwlxuPINc1hpCxpDJn5gqRI8wJf9p1COTlk=,tag:glBXtiSh+jGtkGEfG0/qBQ==,type:str]
    HOMEPAGE_VAR_FRITZBOX_USERNAME: ENC[AES256_GCM,data:AA7wm49wZmGn,iv:Sa4gOzPZVaJe5OiSY4ccCU04SySy5+hI92N/KmKjSyQ=,tag:uXYxvsg3G8y6pH2IHFM80A==,type:str]
    HOMEPAGE_VAR_FRITZBOX_PASSWORD: ENC[AES256_GCM,data:0Ohva5XlDtQ6b5T8P7A=,iv:2hvU9J6oSjC+ykcvTwLxHR3uNOQ7X+VJL5uG5vTCBsA=,tag:JwNSrEIPCklNjLVJfEit6w==,type:str]
    HOMEPAGE_VAR_MIKROTIK_SWITCHING_USERNAME: ENC[AES256_GCM,data:OFFSWcwdc2Y=,iv:NaeSU1AHJRphESIXEC9wAGqvmvxeS/F6epn2nVY52HI=,tag:6OIKTXzaPLcpWO1cA6SDSw==,type:str]
    HOMEPAGE_VAR_MIKROTIK_SWITCHING_PASSWORD: ENC[AES256_GCM,data:iRPWolx0WbttuA9FOInP,iv:k1U4Gip3VQKrQFsbAmS3PKnc9U+BKdfBG+jQ95zuPZY=,tag:JyDLIoS/ZywE5Ur9ZsdOGg==,type:str]
    HOMEPAGE_VAR_MIKROTIK_KUBERNETES_USERNAME: ENC[AES256_GCM,data:sbiww8ajgas=,iv:5xAnxkXQHyLCZgRlYV1ZjHC0j4X9IVp2dm5aGVU/o+s=,tag:QqdGDZYqWXWUGkc09jN7bQ==,type:str]
    HOMEPAGE_VAR_MIKROTIK_KUBERNETES_PASSWORD: ENC[AES256_GCM,data:SIGDDmf8qkT9dISXmdRq,iv:Jx+wcv/uUPm7Yf8CvbxRBeG2WI7hEQidif5Jp7Ut49c=,tag:RtXLjnUaMuIKU4ZYGr3HMA==,type:str]
    HOMEPAGE_VAR_PAPERLESS_TOKEN: ENC[AES256_GCM,data:pqPkDTrUCoWezwDbGyY1LfLzJ/VfWEtbvF2F++zEsg1Ez6trCrI5Gg==,iv:H+VR3/v5X1ltdxbj8FMS8nSfVTWHeozvhsCxpc8F1EM=,tag:WC0WDPI2c0VbB7lq8jjOog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdVpRdTgyOTdSQ29lWEpO
            R2Jxa0FZTm1vTGdVNnkydS9CcS9hK09LL25RClZHUmVtZ1Qxcy9KbStaLzB2Um9P
            UXR0a3lEU0dNeEFYMW11UGIwMUVuTHcKLS0tIDVremFIbXJhZHdOQ210RmtwWlo4
            dmU1MnBreXphZ2ZBb3lRaHAwOUo2aGcKLNMET8drmvMpYN3z8U9nLTQDBYGdtwY/
            oBicI+cZHnu3pX2vv9uBTWW0vCV8nxw1BkhOteNsEhuPtTQUuHFYAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mcj4tr2sfgvc3h2ekqjsvm4s4gh0rs74nqnn0yapfzdtlgkqxysqj6wdrl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T20:08:53Z"
    mac: ENC[AES256_GCM,data:nDYxlj5Q/EgvEpUW8mnwS19QaWSx0bRz1l/yrectqy7xrOHP0q48QWmHM1CR26lOGOcYJaae0ydbRC9VU0F50wxQupY3ZtVm04mV65hR3UiQIDFVywhXIQ5XjY/lNRzwxEHsCb0+FwGkn+cdO2rc2whCINr37K9urOe5xRdTlNg=,iv:BWhLWioG7bPUI2eRk7xhf62GmhzSqEuKU2AfGpnUpME=,tag:H1GJ0uf3Y1I9cE01v6Hj3g==,type:str]
    version: 3.13.1
