apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-consume-nfs
spec:
  capacity:
    storage: 20Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions: [nfsvers=4, hard]
  nfs:
    server: 192.168.178.42
    path: /paperless-consume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume
  namespace: paperless
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  volumeName: paperless-consume-nfs
  resources:
    requests:
      storage: 20Gi
