apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-migration-nfs
spec:
  capacity:
    storage: 50Gi
  accessModes: [ReadOnlyMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions: [nfsvers=4, hard]
  nfs:
    server: 192.168.178.42
    path: /paperless-migration
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-migration
  namespace: paperless
spec:
  accessModes: [ReadOnlyMany]
  storageClassName: ""
  volumeName: paperless-migration-nfs
  resources:
    requests:
      storage: 50Gi
