apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:rT1ocm4rg07PFdzpLQ4PgZybdJuNScQk+MKwRBL5Uko=,iv:KFObKaF/hsUbW3U64z4jyLa/o9PI1ui53m7rb/9obIE=,tag:cUDdaGGw2TM0S7WsYJyXGA==,type:str]
    secret-key: ENC[AES256_GCM,data:/eyUh9at+CD8xCiv0Wxh0IpxNFgfj8OZasxRalUaO8MQ7a2vGWXkzaUJxGXMCD81dZwz8ag1A3R44Z/V70Hypg==,iv:dlziqo8Y71jBEXXhX3YuKFbp497uyUJK4QVfwpnQfXw=,tag:3lsrxgFzJ6RvRli4So/TOg==,type:str]
    export-passphrase: ENC[AES256_GCM,data:bs38fJ91VABJ1+qH2AiACzEsIWHKoJSIFiRmtVaGsMQ=,iv:RST136AImEj9bu9uCYjQaooxLeA2IqGb3jDdM2fNtiA=,tag:b3dvZ2VbA0+3wrC5t4/WYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUnRiMGhza3A5UnJ1MkZv
            bk5oTUpUUUJYekZaN2tQSnk2VFVQYytSdEZrCmg2bFk0UGhYMDFYdTFNMjRTNmpQ
            dHdOcE96ekxlV203VHVNeTdMV2d6ekkKLS0tICtETWM4VTVMWWxLNGpqbWVJdjF1
            Q2ZPUmNWSVRYR1cyK2VZMEpLOGNQM2sK2QIa/5RxpRDuIdCSMemrxIfzZJ/9UNjy
            wnrAUwN5t9At5XW8laQuGW0bDj3K008Rtvk5+NgliaxUh6W3Les2Wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mcj4tr2sfgvc3h2ekqjsvm4s4gh0rs74nqnn0yapfzdtlgkqxysqj6wdrl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T17:10:29Z"
    mac: ENC[AES256_GCM,data:/vym7PziZ+Sfk/4pm38yxpAU9t8mSSsrAZ51Ksbmf3oLl65EYW1utuy1mxsJa7jlQhBOiieBTQA6pMLqJtUoq90263OIB502K+d49N/gxltcCdeKQQz0HhxrUWPDraUQcU1FFcuj2Z3NdOUrsKLvhcouYyelD5hu2u9k4iBgjCc=,iv:fFy4wT8sq0Ns1LPHgGb+suAYkfAHIOtY0UIqZvosbUw=,tag:u1z06SuLTsu30RsKFMOrqg==,type:str]
    version: 3.13.2
