apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-rclone-config
  namespace: paperless
data:
  rclone.conf: |
    [storagebox]
    type = sftp
    host = u620152.your-storagebox.de
    user = u620152-sub1
    port = 23
    key_file = /keys/id_ed25519_hetzner
    shell_type = unix
