apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless-test
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:cWKdPBgJTQ5IxlvdPMZYdRI=,iv:r9f3zNUvyJE5494kzBrxaKvULXmm9J5gVrsnPVWGkdA=,tag:PNk4hUU1GyD1NKJm4vzLhQ==,type:str]
    secret-key: ENC[AES256_GCM,data:0+dlMWoscV9sXbWhhbThbPQWsRip21JNo4dNpygdKRI1J1RPvyUckGryR78GMP0KBTh6EdE+J90VcAUYGZmjsA==,iv:DTDk2Rhw83eH5XQR+YHAd5hk2xlKBNFZNgMuPJU3MHc=,tag:mQc4029FcUj1z2iF+bPk6A==,type:str]
    admin-password: ENC[AES256_GCM,data:I4IkOwzhecV4LFl+ivGL,iv:KYHYY5Y16N15FxXiT5PERPE3/rewV1DGTdh1EvtrHLM=,tag:0nayp2LmPEyCY4IAEqImqQ==,type:str]
    export-passphrase: ENC[AES256_GCM,data:ITo5MbB7H+hX+uKqmRbvmlfmPp47d9wWRfzK6+vIEyY=,iv:jXa5QOPfSaqwJDMoA/EoaHq61j2tCEW+p8e62twbxZo=,tag:4vZ0JKkwTdIZtLihtMXswQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZlZ1QW5NQ1FUdEhPcTZi
            ZGxBaXN4a0swN3gwMXpGZWFlRS9HTlpRckU4CkpuOEZQZW9aQXI0QnREb0lJMDVR
            ck11b2dxdkpqcXJWeElRNS9CVndFVmsKLS0tIDlZR2dsRGQ5VEgrZWdJSkZma0JB
            WStwU2dpaVVTZDMyb2ZISmRJTHFpTDAKNMjgJao87C15ts5hAIvSwtyk4DrCZyI8
            I7F+cOKgHa8Q7F+1CNTnUhhbRsXeIcvH16nDRpjLX3jS3Sx+j1GHMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mcj4tr2sfgvc3h2ekqjsvm4s4gh0rs74nqnn0yapfzdtlgkqxysqj6wdrl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T13:09:20Z"
    mac: ENC[AES256_GCM,data:wW2CHQ590QwL1rlYopJijop9T4Div2/7oozvVUeNLVAINPomkpbE4joIRRofqn7Jqy41goZIOjvMsQNiCPmtDkxabed0sk/0gQlJRCLgWH3kV9iOLm+arEY4353teoBwcxT+bAHErsQnLbsXKbLNuU8CP5PR8xPMbDnHOIl6TH0=,iv:TLCmJmfHO82u+E6UOk0rO12cMRImezQjojxibmFW1j4=,tag:fe3hPdMzYOFezq5nDaAl+g==,type:str]
    version: 3.13.3
