apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: paperless-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-iscsi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
  namespace: paperless-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-iscsi
  resources:
    requests:
      # Spiegel des Produktivbestands -> gleiche Größenordnung wie Produktiv-media (50Gi)
      storage: 50Gi
