apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Liihi8/vGaqn47p4AsCubuUdMXMmnN+IJeX70Yrp3IqGiKct67OQNBrJT4oWmT1c39pLkNOhAQ3Jj5xTfGaEe4KQCBdJB2eodEAl9eKHJK/qecPL8OukgUwDgQpZiQrjl+cKM0NPJjgq8f1P65uPDYqtmE1o8pELsXR5PE4o6Ls+rUS4F//pJ2Sf9wIalH2SsxDE+gs/SMy4ssLTewgLqJ1JS1YnKVEMoS3ElM/ldVbRXmA6rGW7if/bvptq7+DPMKXesPN0hIxg6ywOa1VBQW/Pk1sc9SmHeqlh54rnJyJ3OhQ8BLzlG7T36tM=,iv:tIJ3pA0nXoJ2kvPEPYx2/bkx977PgiG5m5xt+l41qkA=,tag:+stSzBl6LKgA0J2QiNykZA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1c8x9n79ak4ss8wv45aexsf8r7w8w6mt6hvneu58hqrazdd2syc8q968jyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVTl1WEtPM0daL09PenlN
            VHp5Q1dtazhocElKNm9ucjhzNnFlSC9MdEdBCi9ISFpmT1czT0dBM0NOd3hPNTF1
            Ry9mRVZ4VlRSRzJkNktKZG9yVDd4NjAKLS0tIFRtYW5uWW0ycUgxMXFQMWQwL3c4
            OGlRbFFLTGc1ak4rSHQwY3BZMU9yNVEKcM9xcRLZPdf/QKmIMYjZTsd0rC5caygh
            T96IqB2UTl+vVW1E1spl1CTOXCAM2klK3HshhmldBgeE4kPvuxAxQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T16:12:50Z"
    mac: ENC[AES256_GCM,data:z0ni5Dv/HiIRL2aJNY0QdxCGuyShSBsVDneFOKKMH0fjhys+MIGHsKbY4ACetCQ7jNJGIR4d622blkIfHqlOaT5ilIrE1cOe8B5jyCnvJd7y2Qb4rn7Ft76assdr+i0xYQYcl09sHJ5XagRHC1zqtq7uXh32FAy/hormdeNQFoc=,iv:+BJANFAZpBPd1H3gAIIQS4t313r+pN728cU5/Umx7iY=,tag:+EQuu+FlS72q7eLpzw181A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
