apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    tunnel: f67d44d7-f8e6-4ebd-abad-6bb436226a68
    credentials-file: /etc/cloudflared/creds/credentials.json
    no-autoupdate: true
    protocol: http2
    ingress:
      - service: http://cilium-gateway-pantheon-gateway.default.svc.cluster.local:80
