apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflare
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:HkhxZTWF0M40RHCh2+mEGCbNW0qAnoTBGzs5JMNDoA/iThqcKbtgInnf3c1omVveSdosvZgOe5GvGQO8DM/IcbgKV22s+V9L8dNyB0oLKNhsGvZD8R+cNY6KzQ3guMVZLMo5d08Sr3u5uYtR7I3KY/6bHNFUJy8wqanMpJZxN6RymzlcXDFZjCnWEHKWexH6L5Ntlk+bqNkt+kfQAiXsIzX00yTjeFHiiXWwTE1Hng==,iv:wQ6XEw3t78f4gthP4UVFFFI8n8dHDZHX+/W1evcSxN0=,tag:FhYUoGkLTtuByKhg31q6cA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaUdYWW1HcTFCM3B2dlp1
            NkYwRUhIYnNyTTI4NjBTMzUyMnAwa0Era3cwCko2bWFhM21ya2FjZGhoUkNjaUNH
            aGxyLzBaTVdFV0lYakhwK2xwamFiZ2MKLS0tIDAzalRQRDRNZ2d6Ky9wNVZGc0wx
            UzcrTEdKbDBFeDRyaGZBTzFsZGVnaFEKaUevKuANb4L1ONiSdjkdaQI7j1mTuG/f
            ejud0nXaUSKBM/VTz+2pGWQWSG5Qfi2P3vit1G19AnoEGeRUBg+wZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mcj4tr2sfgvc3h2ekqjsvm4s4gh0rs74nqnn0yapfzdtlgkqxysqj6wdrl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T18:17:18Z"
    mac: ENC[AES256_GCM,data:aYSL1k5pWFSWQgRnoW5Hj6nW/DZ3WvbFppJYE+AU1iUs9+sgADXcuSeBX4W3/sJhnO2OoZsVQ8ACDf5dGd4T1WqU2MT4xJqSswKv3jahjV+xt6ZHmV7q0okK7jxzDu8d4afOp3sFu5EJ+Mo/xJ7HezRaVlGzllij48sj62S2634=,iv:vcqoR6AjxDX6FLKLITbJ6ZEmCM22d9+B0tarj+Ssj/g=,tag:Q1qDYKAf9CobYSOR+/qHxg==,type:str]
    version: 3.13.2
