apiVersion: trident.qnap.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-qnap
  namespace: trident
spec:
  version: 1
  storageDriverName: qnap-nas
  backendName: pantheon-qnap
  credentials:
    name: backend-qnap-secret
