apiVersion: trident.qnap.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-qnap
  namespace: trident
spec:
  version: 1
  storageDriverName: qnap-iscsi
  backendName: qnap-iscsi
  credentials:
    name: backend-qnap-secret
  storage:
    - labels:
        performance: standard
      serviceLevel: pool1 # MUSS dem QNAP-internen Pool-Namen entsprechen!
      features:
        tiering: "Disable" # einzelner Pool, kein Tiering
      defaults:
        spaceAllocation: "true"
        snapshotPolicy: none
