apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: qnap-csi
  namespace: trident
spec:
  interval: 1h
  url: https://github.com/qnap-dev/QNAP-CSI-PlugIn
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qnap-trident
  namespace: trident
spec:
  interval: 1h
  chart:
    spec:
      chart: Helm/trident
      sourceRef:
        kind: GitRepository
        name: qnap-csi
