apiVersion: v1
kind: Secret
metadata:
    name: backend-qnap-secret
    namespace: trident
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:rIEnwa0=,iv:cMNL0kl6P46eV1/Eyr+NV5fpivUBWwYTeWv1neb13so=,tag:4jU+qoX8wA0dPo5eq4kSlw==,type:str]
    password: ENC[AES256_GCM,data:oWeoOsfsCLMq8J3QdLI73e5P,iv:zJ3rQEBEnmsM6H1yetp2RaLaQac/1qXSAgYjUYj2788=,tag:WK2LZB73fF39nBp8qHyKLA==,type:str]
    storageAddress: ENC[AES256_GCM,data:2z4mw5XQM1kWleuSzYY=,iv:Kpk3d7ZM3zMJNlEZeCXHhe3Kl0JMaLcvJsDLFpsnOM4=,tag:dtTNHZmavA42MWkJVHMC2w==,type:str]
    https: ENC[AES256_GCM,data:iHaa/Zs=,iv:piGn4a53nKO9bP5tWZaz2IG0BkithLVSYbmXhkCyQjw=,tag:r7T7g5HHwVo4pKzClEaI+w==,type:str]
    port: ENC[AES256_GCM,data:q2uzAQ==,iv:gwy6Bv7/g3yH7uQppW8idgNKxp3gw2D2IUCVZCoLFDw=,tag:9snsSnizIc5nnuwXRnUOtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhamk1cldPdllkUVhXb3dP
            bHphUDU1QVFiZis3NElNaloyMFp2cUZUS1hzClhDM0dJMm9vZytka0VsK0ZxS3JZ
            ditTUnFlVXFEMEdRRTdxZFpEYVNYQVEKLS0tIDNod2lHeEhKN0JPeUZzd05uYW0x
            UERmRk5ka1BUSzdLdGZIVUpOL0ljcUkK6b1E1yzac5M0kH8/+N1wzHmyr1Kqe7G7
            STwyT4irYGlOVq6/yqS7yEFqyIc/22inmkPX/OhhNDzXVn/5GRNt0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mcj4tr2sfgvc3h2ekqjsvm4s4gh0rs74nqnn0yapfzdtlgkqxysqj6wdrl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T09:56:13Z"
    mac: ENC[AES256_GCM,data:l+TeAycGdIDTGj9q8iWuz12IguYgB3a+XFKAtjQgRCcRm/YLTkiXHOeCHhLEqC9F91ebkwmI1yKcgc2yrzviAV/m3IQJ1rnwnJq6Fi+uTMzSXHDdsoJiud2JNijqu0MrR2929EsoE4sJNKelQXFDrML7ZrvdmOADuYJOHSES3eA=,iv:xPWr5ga/MoAtETjr/+p9DtprLApemIV94eqCSah6tBE=,tag:6P4/xyIaWCiQuFeyigAc9Q==,type:str]
    version: 3.13.1
