name: Validate Omni Cluster Template

on:
  pull_request:
    paths:
      - "omni/**"
  workflow_dispatch:

jobs:
  validate:
    runs-on: [self-hosted, omni-lan]
    name: Validate cluster template
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Validate cluster template
        working-directory: ./omni/
        env:
          OMNI_ENDPOINT: ${{ secrets.OMNI_ENDPOINT }}
          OMNI_SERVICE_ACCOUNT_KEY: ${{ secrets.OMNI_SERVICE_ACCOUNT_KEY }}
        run: omnictl cluster template -f cluster-template-pantheon.yaml validate
