name: Sync Omni Cluster Template

on:
  push:
    branches: [main]
    paths:
      - "omni/**"
  workflow_dispatch:

jobs:
  sync:
    runs-on: [self-hosted, omni-lan]
    name: Sync cluster template with Sidero Omni
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Sync cluster template
        working-directory: ./omni/
        env:
          OMNI_ENDPOINT: ${{ secrets.OMNI_ENDPOINT }}
          OMNI_SERVICE_ACCOUNT_KEY: ${{ secrets.OMNI_SERVICE_ACCOUNT_KEY }}
        run: omnictl cluster template -f cluster-template-pantheon.yaml sync --verbose
