apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:ezHGimslB661Xj6A2OmVr3UqtoXspByrg8MgHv5/rFnK7KR+2hr76R7H5MLbGPTDBwEX2Orrv24=,iv:+DQzQAAPtnDlcnFYNRrTdvh9VVyMfYWZ8P21A+cqAjo=,tag:csM3lyhnbjUBCx0exWmvMg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    age:
        - recipient: age1c8x9n79ak4ss8wv45aexsf8r7w8w6mt6hvneu58hqrazdd2syc8q968jyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVW1tTEIzZDdQaW11eE5j
            dWtGdXpKUmRVU3M4N3BYRFZOZENnVVFXTlRZCkxtWXZEcERYVXR6S0hwZXFzbWl4
            a2hPaklGSENONWpuYjlSUVZXTGxndjAKLS0tIEZXSEdIYXdLTmlhaysrYzhmTmNY
            bTMybGZHaXBoS3NFenNiZ1pSUlJzN0kKwORGdR7NAVFhNfK2oWNuqlfdrTxluWNH
            ttZUvr2FyfBXh+C5BbiZaw8Sb5w++SoZ+CWNce5+5WMNk7+2flFinQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T11:29:34Z"
    mac: ENC[AES256_GCM,data:Zol3zAb9JVDKkmM8GnbOVpRI2WwmrBUAXzqy4ix0FeeQyC/xeXz546UZ6nDXnflhTfREkdR/Umup7l7UHS9RHGCFlKPi/pK89ofsKhSXWS5tMgYN+icyb3jCetdPr4L3ej5eTLaP+rjO3pbJPcDOpveBgTi8L92tUAs6QSab838=,iv:0Gt2ek0UrkyfQgUGWy5B0LfiHYRiSznxsDmkuJYTyso=,tag:wpdQumzJ0QohRV1QOG24Qg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
